CREATE VIEW `ods_view.view_ods_flume_json_db__table` AS select `ods_flume_json_db__table`.`datelabel`
, `json`.`mysql_op_type`
, `json`.`id`
, `json`.`version`
, `json`.`is_modify`
, `json`.`sku_code`
, `json`.`shop_code`
, `json`.`sku_alias`
, `json`.`group_code`
, `json`.`is_gift`
, `json`.`sku_status`
, `json`.`valid_flag`
, `json`.`sku_form`
, `json`.`is_seasional_sku`
, `json`.`recommended_begin_date`
, `json`.`recommended_end_date`
, `json`.`evaluation_code`
, `json`.`supplier_code`
, `json`.`operate_mode`
, `json`.`purchase_strategy`
, `json`.`permanent_price`
, `json`.`sale_channel`
, `json`.`sale_cess_code`
, `json`.`sale_min_num`
, `json`.`is_sale_min_price`
, `json`.`min_price`
, `json`.`is_member_discount`
, `json`.`is_member_integral`
, `json`.`is_coupon`
, `json`.`max_stock`
, `json`.`min_stock`
, `json`.`safe_stock`
, `json`.`valuation_code`
, `json`.`in_warehouse_deadline`
, `json`.`out_warehouse_deadline`
, `json`.`is_negative_stock`
, `json`.`floor`
, `json`.`surface`
, `json`.`deep`
, `json`.`family_group`
, `json`.`is_del`
, `json`.`create_by`
, `json`.`create_at`
, `json`.`update_by`
, `json`.`update_at`
, `json`.`last_updated_at`


from `ods`.`ods_flume_json_db__table`
lateral view json_tuple(`ods_flume_json_db__table`.`json_str`
, "mysql_op_type"
, "id"
, "version"
, "is_modify"
, "sku_code"
, "shop_code"
, "sku_alias"
, "group_code"
, "is_gift"
, "sku_status"
, "valid_flag"
, "sku_form"
, "is_seasional_sku"
, "recommended_begin_date"
, "recommended_end_date"
, "evaluation_code"
, "supplier_code"
, "operate_mode"
, "purchase_strategy"
, "permanent_price"
, "sale_channel"
, "sale_cess_code"
, "sale_min_num"
, "is_sale_min_price"
, "min_price"
, "is_member_discount"
, "is_member_integral"
, "is_coupon"
, "max_stock"
, "min_stock"
, "safe_stock"
, "valuation_code"
, "in_warehouse_deadline"
, "out_warehouse_deadline"
, "is_negative_stock"
, "floor"
, "surface"
, "deep"
, "family_group"
, "is_del"
, "create_by"
, "create_at"
, "update_by"
, "update_at"
, "last_updated_at"
) `json` as `mysql_op_type`
, `id`
, `version`
, `is_modify`
, `sku_code`
, `shop_code`
, `sku_alias`
, `group_code`
, `is_gift`
, `sku_status`
, `valid_flag`
, `sku_form`
, `is_seasional_sku`
, `recommended_begin_date`
, `recommended_end_date`
, `evaluation_code`
, `supplier_code`
, `operate_mode`
, `purchase_strategy`
, `permanent_price`
, `sale_channel`
, `sale_cess_code`
, `sale_min_num`
, `is_sale_min_price`
, `min_price`
, `is_member_discount`
, `is_member_integral`
, `is_coupon`
, `max_stock`
, `min_stock`
, `safe_stock`
, `valuation_code`
, `in_warehouse_deadline`
, `out_warehouse_deadline`
, `is_negative_stock`
, `floor`
, `surface`
, `deep`
, `family_group`
, `is_del`
, `create_by`
, `create_at`
, `update_by`
, `update_at`
, `last_updated_at`